# Site
repository: cuonghapvn/cuonghapvn.github.io
favicon: images/favicon.ico

# Personal info
name: Cuong Nguyen
title: Project Manager | Senior Full-stack Developer
email: cuonghapvn@gmail.com
website: https://www.cuongn.com

# Social links
# twitter_username: facespics
github_username:  cuonghapvn
# dribbble_username: jekyll
facebook_username: ceno239
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: nguyen-cuong-92988332
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Cuong Nguyen and I'm a senior fullstack web developer. As well as developing web systems I also have experience managing project in both traditional and agile. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Java</mark>, <mark>NodeJS</mark> and <mark>Project Management</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
